### PR TITLE
Johntests

### PR DESCRIPTION
**Pull request by JohnGordinier**
Completed two tests for the server and will continue tomorrow. Merged with Main 10 minutes ago and verified site validation and functionality.

### CODE REVIEW

**Comment by JohnGordinier** [comment]
Code testing complete with 3 tests to 3 separate CRUD functions: get all commands, get all categories, get all commands from a unique category, as well as an Admin Login test for token, username, and hash password. The only addition is an "admin_accounts" table that was added to the migration.sql. Storage was needed for future accounts plus it's needed for temp storage of the test run. A slight update was added to the server.js for admin functionality. NEEDED for this: A database named: "quest_test" with the migration.sql run into it which has the new table "admin_accounts"

**Comment by JohnGordinier** [comment]
It's merged and works again with the lastest commit. There is redundant coding in the server.js that occurs with each main pull. Simply removing the redundancy fixes the server issue.

**Comment by mnorthup28** [comment]
I looked through this and still can't get it to pass. I have tried making tweaks myself and can't get it to work either. If someone else has more experience with testing this may be a good job for them.

**Review by mnorthup28 — APPROVED** [review]
Working now. Need to make sure the ENV variables are matching and you do a npm install, but it is working.

**Comment by shannonscotta** [comment]
close but needs to have current main but we bring everything over

**Comment by JohnGordinier** [comment]
Correct.

**Pull request closed without merging**
