### PR TITLE
87 hook up ai chatbot to quest

### PR DESCRIPTION
**Pull request by AGI-CEO**
image
Chatbot UI works, next step is to enable markdown formatting to be rendered since the AI API will sometimes return styled responses in markdown.

image
The console logs have been commented out but can be commented to test responses. The Render instance is very slow so responses take a while. The logs help with testing to see if it's the render AI API being slow or if it's the quest app.

### CODE REVIEW

**Review by kajiwara12 — DISMISSED** [review]
looks good to me

**Comment by gnprwx** [comment]
@AGI-CEO Converting markdown should be fixable with tailwind's typography plugin, which converts markdown to html.

**Comment by AGI-CEO** [comment]
> @AGI-CEO Converting markdown should be fixable with tailwind's typography plugin, which converts markdown to html.

I'll take a look tomorrow.

The library I was looking at was react-markdown (https://remarkjs.github.io/react-markdown/)

**Comment by gnprwx** [comment]
> > @AGI-CEO Converting markdown should be fixable with tailwind's typography plugin, which converts markdown to html.
> 
> I'll take a look tomorrow.
> 
> The library I was looking at was react-markdown (https://remarkjs.github.io/react-markdown/)

https://tailwindcss.com/docs/typography-plugin

Ok, cool. Try it out for the sake of already using tailwind. If anything, we can pair up on this one and check it out. I already use it on my own website so I am familiar with its functionality.

**Comment by shannonscotta** [comment]
Need to see the your .env to test locally before approving

**Comment by AGI-CEO** [comment]
> Need to see the your .env to test locally before approving

https://discord.com/channels/1176637970460192870/1176637972817395786/1191897150322397274

**Comment by shannonscotta** [comment]
> > Need to see the your .env to test locally before approving
> 
> https://discord.com/channels/1176637970460192870/1176637972817395786/1191897150322397274

Doesn't work locally with what is provided in the general chat

**Review by shannonscotta — APPROVED** [review]

**Pull request merged**
